import { Lexend } from "next/font/google";  // Importing a supported font
import "./globals.css";

// Initialize the Lexend font
const lexend = Lexend({
  variable: "--font-lexend",  // Custom variable to use the font
  subsets: ["latin"],  // Specify the subsets (like Latin characters)
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
